import sys
import pypff

OUTLOOK_DATA_FILE = 1
DELETED = 0
INBOX = 1

# /* The entry types
 # */
# enum LIBPFF_ENTRY_TYPES
# {
	# LIBPFF_ENTRY_TYPE_MESSAGE_IMPORTANCE					= 0x0017,

	# LIBPFF_ENTRY_TYPE_MESSAGE_CLASS						= 0x001a,

	# LIBPFF_ENTRY_TYPE_MESSAGE_PRIORITY					= 0x0026,

	# LIBPFF_ENTRY_TYPE_MESSAGE_SENSITIVITY					= 0x0036,
	# LIBPFF_ENTRY_TYPE_MESSAGE_SUBJECT					= 0x0037,

	# LIBPFF_ENTRY_TYPE_MESSAGE_CLIENT_SUBMIT_TIME				= 0x0039,

	# LIBPFF_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_SEARCH_KEY			= 0x003b,

	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_BY_ENTRY_IDENTIFIER			= 0x003f,
	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_BY_NAME				= 0x0040,
	# LIBPFF_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_ENTRY_IDENTIFIER		= 0x0041,
	# LIBPFF_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_NAME			= 0x0042,
	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_ENTRY_IDENTIFIER	= 0x0043,
	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_NAME			= 0x0044,

	# LIBPFF_ENTRY_TYPE_MESSAGE_REPLY_RECIPIENT_ENTRIES			= 0x004f,
	# LIBPFF_ENTRY_TYPE_MESSAGE_REPLY_RECIPIENT_NAMES				= 0x0050,
	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_BY_SEARCH_KEY			= 0x0051,
	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_SEARCH_KEY		= 0x0052,

	# LIBPFF_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_ADDRESS_TYPE		= 0x0064,
	# LIBPFF_ENTRY_TYPE_MESSAGE_SENT_REPRESENTING_EMAIL_ADDRESS		= 0x0065,

	# LIBPFF_ENTRY_TYPE_MESSAGE_CONVERSATION_TOPIC				= 0x0070,
	# LIBPFF_ENTRY_TYPE_MESSAGE_CONVERSATION_INDEX				= 0x0071,

	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_BY_ADDRESS_TYPE			= 0x0075,
	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_BY_EMAIL_ADDRESS			= 0x0076,
	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_ADDRESS_TYPE		= 0x0077,
	# LIBPFF_ENTRY_TYPE_MESSAGE_RECEIVED_REPRESENTING_EMAIL_ADDRESS		= 0x0078,

	# LIBPFF_ENTRY_TYPE_MESSAGE_TRANSPORT_HEADERS				= 0x007d,

	# LIBPFF_ENTRY_TYPE_RECIPIENT_TYPE					= 0x0c15,

	# LIBPFF_ENTRY_TYPE_MESSAGE_SENDER_ENTRY_IDENTIFIER			= 0x0c19,
	# LIBPFF_ENTRY_TYPE_MESSAGE_SENDER_NAME					= 0x0c1a,

	# LIBPFF_ENTRY_TYPE_MESSAGE_SENDER_SEARCH_KEY				= 0x0c1d,
	# LIBPFF_ENTRY_TYPE_MESSAGE_SENDER_ADDRESS_TYPE				= 0x0c1e,
	# LIBPFF_ENTRY_TYPE_MESSAGE_SENDER_EMAIL_ADDRESS				= 0x0c1f,

	# LIBPFF_ENTRY_TYPE_MESSAGE_DISPLAY_TO					= 0x0e04,

	# LIBPFF_ENTRY_TYPE_MESSAGE_DELIVERY_TIME					= 0x0e06,
	# LIBPFF_ENTRY_TYPE_MESSAGE_FLAGS						= 0x0e07,
	# LIBPFF_ENTRY_TYPE_MESSAGE_SIZE						= 0x0e08,

	# LIBPFF_ENTRY_TYPE_MESSAGE_STATUS					= 0x0e17,

	# LIBPFF_ENTRY_TYPE_ATTACHMENT_SIZE					= 0x0e20,

	# LIBPFF_ENTRY_TYPE_MESSAGE_INTERNET_ARTICLE_NUMBER			= 0x0e23,

	# LIBPFF_ENTRY_TYPE_MESSAGE_PERMISSION					= 0x0e27,

	# LIBPFF_ENTRY_TYPE_MESSAGE_URL_COMPUTER_NAME_SET				= 0x0e62,

	# LIBPFF_ENTRY_TYPE_MESSAGE_TRUST_SENDER					= 0x0e79,

	# LIBPFF_ENTRY_TYPE_MESSAGE_BODY_PLAIN_TEXT				= 0x1000,

	# LIBPFF_ENTRY_TYPE_MESSAGE_BODY_COMPRESSED_RTF				= 0x1009,

	# LIBPFF_ENTRY_TYPE_MESSAGE_BODY_HTML					= 0x1013,

	# LIBPFF_ENTRY_TYPE_EMAIL_EML_FILENAME					= 0x10f3,

	# LIBPFF_ENTRY_TYPE_DISPLAY_NAME						= 0x3001,
	# LIBPFF_ENTRY_TYPE_ADDRESS_TYPE						= 0x3002,
	# LIBPFF_ENTRY_TYPE_EMAIL_ADDRESS						= 0x3003,

	# LIBPFF_ENTRY_TYPE_MESSAGE_CREATION_TIME					= 0x3007,
	# LIBPFF_ENTRY_TYPE_MESSAGE_MODIFICATION_TIME				= 0x3008,

	# LIBPFF_ENTRY_TYPE_MESSAGE_STORE_VALID_FOLDER_MASK			= 0x35df,

	# LIBPFF_ENTRY_TYPE_FOLDER_TYPE						= 0x3601,
	# LIBPFF_ENTRY_TYPE_NUMBER_OF_CONTENT_ITEMS				= 0x3602,
	# LIBPFF_ENTRY_TYPE_NUMBER_OF_UNREAD_CONTENT_ITEMS			= 0x3603,

	# LIBPFF_ENTRY_TYPE_HAS_SUB_FOLDERS					= 0x360a,

	# LIBPFF_ENTRY_TYPE_CONTAINER_CLASS					= 0x3613,

	# LIBPFF_ENTRY_TYPE_NUMBER_OF_ASSOCIATED_CONTENT				= 0x3617,

	# LIBPFF_ENTRY_TYPE_ATTACHMENT_DATA_OBJECT				= 0x3701,

	# LIBPFF_ENTRY_TYPE_ATTACHMENT_FILENAME_SHORT				= 0x3704,
	# LIBPFF_ENTRY_TYPE_ATTACHMENT_METHOD					= 0x3705,

	# LIBPFF_ENTRY_TYPE_ATTACHMENT_FILENAME_LONG				= 0x3707,

	# LIBPFF_ENTRY_TYPE_ATTACHMENT_RENDERING_POSITION				= 0x370b,

	# LIBPFF_ENTRY_TYPE_CONTACT_CALLBACK_PHONE_NUMBER				= 0x3a02,

	# LIBPFF_ENTRY_TYPE_CONTACT_GENERATIONAL_ABBREVIATION			= 0x3a05,
	# LIBPFF_ENTRY_TYPE_CONTACT_GIVEN_NAME					= 0x3a06,

	# LIBPFF_ENTRY_TYPE_CONTACT_BUSINESS_PHONE_NUMBER_1			= 0x3a08,
	# LIBPFF_ENTRY_TYPE_CONTACT_HOME_PHONE_NUMBER				= 0x3a09,
	# LIBPFF_ENTRY_TYPE_CONTACT_INITIALS					= 0x3a0a,

	# LIBPFF_ENTRY_TYPE_CONTACT_SURNAME					= 0x3a11,

	# LIBPFF_ENTRY_TYPE_CONTACT_POSTAL_ADDRESS				= 0x3a15,
	# LIBPFF_ENTRY_TYPE_CONTACT_COMPANY_NAME					= 0x3a16,
	# LIBPFF_ENTRY_TYPE_CONTACT_JOB_TITLE					= 0x3a17,
	# LIBPFF_ENTRY_TYPE_CONTACT_DEPARTMENT_NAME				= 0x3a18,
	# LIBPFF_ENTRY_TYPE_CONTACT_OFFICE_LOCATION				= 0x3a19,
	# LIBPFF_ENTRY_TYPE_CONTACT_PRIMARY_PHONE_NUMBER				= 0x3a1a,
	# LIBPFF_ENTRY_TYPE_CONTACT_BUSINESS_PHONE_NUMBER_2			= 0x3a1b,
	# LIBPFF_ENTRY_TYPE_CONTACT_MOBILE_PHONE_NUMBER				= 0x3a1c,

	# LIBPFF_ENTRY_TYPE_CONTACT_BUSINESS_FAX_NUMBER				= 0x3a24,

	# LIBPFF_ENTRY_TYPE_CONTACT_COUNTRY					= 0x3a26,
	# LIBPFF_ENTRY_TYPE_CONTACT_LOCALITY					= 0x3a27,

	# LIBPFF_ENTRY_TYPE_CONTACT_TITLE						= 0x3a45,

	# LIBPFF_ENTRY_TYPE_MESSAGE_BODY_CODEPAGE					= 0x3fde,

	# LIBPFF_ENTRY_TYPE_MESSAGE_CODEPAGE					= 0x3ffd,

	# LIBPFF_ENTRY_TYPE_RECIPIENT_DISPLAY_NAME				= 0x5ff6,

	# LIBPFF_ENTRY_TYPE_FOLDER_CHILD_COUNT					= 0x6638,

	# LIBPFF_ENTRY_TYPE_SUB_ITEM_IDENTIFIER					= 0x67f2,

	# LIBPFF_ENTRY_TYPE_MESSAGE_STORE_PASSWORD_CHECKSUM			= 0x67ff,

	# LIBPFF_ENTRY_TYPE_ADDRESS_FILE_UNDER					= 0x8005,

	# LIBPFF_ENTRY_TYPE_DISTRIBUTION_LIST_NAME				= 0x8053,
	# LIBPFF_ENTRY_TYPE_DISTRIBUTION_LIST_MEMBER_ONE_OFF_ENTRY_IDENTIFIERS	= 0x8054,
	# LIBPFF_ENTRY_TYPE_DISTRIBUTION_LIST_MEMBER_ENTRY_IDENTIFIERS		= 0x8055,

	# LIBPFF_ENTRY_TYPE_CONTACT_EMAIL_ADDRESS_1				= 0x8083,

	# LIBPFF_ENTRY_TYPE_CONTACT_EMAIL_ADDRESS_2				= 0x8093,

	# LIBPFF_ENTRY_TYPE_CONTACT_EMAIL_ADDRESS_3				= 0x80a3,

	# LIBPFF_ENTRY_TYPE_TASK_STATUS						= 0x8101,
	# LIBPFF_ENTRY_TYPE_TASK_PERCENTAGE_COMPLETE				= 0x8102,

	# LIBPFF_ENTRY_TYPE_TASK_START_DATE					= 0x8104,
	# LIBPFF_ENTRY_TYPE_TASK_DUE_DATE						= 0x8105,

	# LIBPFF_ENTRY_TYPE_TASK_ACTUAL_EFFORT					= 0x8110,
	# LIBPFF_ENTRY_TYPE_TASK_TOTAL_EFFORT					= 0x8111,
	# LIBPFF_ENTRY_TYPE_TASK_VERSION						= 0x8112,

	# LIBPFF_ENTRY_TYPE_TASK_IS_COMPLETE					= 0x811c,

	# LIBPFF_ENTRY_TYPE_TASK_IS_RECURRING					= 0x8126,

	# LIBPFF_ENTRY_TYPE_APPOINTMENT_BUSY_STATUS				= 0x8205,

	# LIBPFF_ENTRY_TYPE_APPOINTMENT_LOCATION					= 0x8208,

	# LIBPFF_ENTRY_TYPE_APPOINTMENT_START_TIME				= 0x820d,
	# LIBPFF_ENTRY_TYPE_APPOINTMENT_END_TIME					= 0x820e,

	# LIBPFF_ENTRY_TYPE_APPOINTMENT_DURATION					= 0x8213,

	# LIBPFF_ENTRY_TYPE_APPOINTMENT_IS_RECURRING				= 0x8223,

	# LIBPFF_ENTRY_TYPE_APPOINTMENT_RECURRENCE_PATTERN			= 0x8232,

	# LIBPFF_ENTRY_TYPE_APPOINTMENT_TIMEZONE_DESCRIPTION			= 0x8234,
	# LIBPFF_ENTRY_TYPE_APPOINTMENT_FIRST_EFFECTIVE_TIME			= 0x8235,
	# LIBPFF_ENTRY_TYPE_APPOINTMENT_LAST_EFFECTIVE_TIME			= 0x8236,

	# LIBPFF_ENTRY_TYPE_MESSAGE_REMINDER_TIME					= 0x8502,
	# LIBPFF_ENTRY_TYPE_MESSAGE_IS_REMINDER					= 0x8503,

	# LIBPFF_ENTRY_TYPE_MESSAGE_IS_PRIVATE					= 0x8506,

	# LIBPFF_ENTRY_TYPE_MESSAGE_REMINDER_SIGNAL_TIME				= 0x8550
# };

# enum LIBPFF_VALUE_TYPES
# {
	# LIBPFF_VALUE_TYPE_UNSPECIFIED						= 0x0000,
	# LIBPFF_VALUE_TYPE_NULL							= 0x0001,
	# LIBPFF_VALUE_TYPE_INTEGER_16BIT_SIGNED					= 0x0002,
	# LIBPFF_VALUE_TYPE_INTEGER_32BIT_SIGNED					= 0x0003,
	# LIBPFF_VALUE_TYPE_FLOAT_32BIT						= 0x0004,
	# LIBPFF_VALUE_TYPE_DOUBLE_64BIT						= 0x0005,
	# LIBPFF_VALUE_TYPE_CURRENCY						= 0x0006,
	# LIBPFF_VALUE_TYPE_FLOATINGTIME						= 0x0007,
	# LIBPFF_VALUE_TYPE_ERROR							= 0x000a,
	# LIBPFF_VALUE_TYPE_BOOLEAN						= 0x000b,
	# LIBPFF_VALUE_TYPE_OBJECT						= 0x000d,
	# LIBPFF_VALUE_TYPE_INTEGER_64BIT_SIGNED					= 0x0014,
	# LIBPFF_VALUE_TYPE_STRING_ASCII						= 0x001e,
	# LIBPFF_VALUE_TYPE_STRING_UNICODE					= 0x001f,
	# LIBPFF_VALUE_TYPE_FILETIME						= 0x0040,
	# LIBPFF_VALUE_TYPE_GUID							= 0x0048,
	# LIBPFF_VALUE_TYPE_SERVER_IDENTIFIER					= 0x00fb,
	# LIBPFF_VALUE_TYPE_RESTRICTION						= 0x00fd,
	# LIBPFF_VALUE_TYPE_RULE_ACTION						= 0x00fe,
	# LIBPFF_VALUE_TYPE_BINARY_DATA						= 0x0102,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_INTEGER_16BIT_SIGNED			= 0x1002,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_INTEGER_32BIT_SIGNED			= 0x1003,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_FLOAT_32BIT				= 0x1004,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_DOUBLE_64BIT				= 0x1005,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_CURRENCY					= 0x1006,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_FLOATINGTIME				= 0x1007,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_INTEGER_64BIT_SIGNED			= 0x1014,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_STRING_ASCII				= 0x101e,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_STRING_UNICODE				= 0x101f,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_FILETIME					= 0x1040,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_GUID					= 0x1048,
	# LIBPFF_VALUE_TYPE_MULTI_VALUE_BINARY_DATA				= 0x1102
# };


def main():
    pff_file = pypff.file()
    pff_file.open("sherriffsv@virtualsystems.eu.com.pst")

    root_folder = pff_file.get_root_folder()
    
    outlook = root_folder.get_sub_folder(OUTLOOK_DATA_FILE)
    inbox = outlook.get_sub_folder(INBOX)
    
    print "[*] Inbox message count: %d" % inbox.get_number_of_sub_messages()
    
    for index in range(0, 1):
        msg = inbox.get_sub_message(index)
        sender = msg.get_sender_name()
        subject = msg.get_subject()
        attachments = msg.get_number_of_attachments()

        print msg.get_record_set(0).get_entry(1).get_entry_type()
        print msg.get_record_set(0).get_entry(1).get_data_as_string()

        if attachments > 0:
            print "!",

        if subject is not None:
            print u"[%s]" % subject.encode(errors="replace"),
        else:
            print "[no subject]",
           
        if sender is not None:
            print u" (%s) " % sender.encode(errors="replace")

    pff_file.close()
    
if __name__ == "__main__":
	main()